### ISSUE TITLE
Interactive phone number and email in the main section

### ISSUE THREAD

**Issue by mecies** [KonradSzwarc/devscard#208]
**Is your feature request related to a problem? Please describe.**
The phone number and email on the main section are not clickable (by design).

**Describe the solution you'd like**
Add an option to convert the email and phone number to `<a>` with `mailto:` and `tel:`

**Describe alternatives you've considered**
None 😂 

**Additional context**
![Screenshot 2023-03-03 at 15 06 48](https://user-images.githubusercontent.com/39158460/222740761-37636b61-276a-41ae-934f-4aedf7e299f8.png)

**Comment by CaptainObjective** [comment]
Hello, @mecies. Thanks for raising this issue!

The feature you request is already implemented. To convert the value into a link simply set `url` property to the destination of your choice, it can be `http`, `mailto`, `tel` or any other schema recognizable by the browser. You can read more about this here: [link](https://github.com/KonradSzwarc/devscard/blob/main/src/types/shared.ts#L56)

That being said, we found room for improvement in this area. Namely, `target` attribute should be set to `_blank` only for HTTP links.

Also, sample data should indicate that it is possible to convert this value into a link.

I raised the PR with said improvements. Again thanks for raising this issue!

**Comment by mecies** [comment]
> Hello, @mecies. Thanks for raising this issue!
> 
> The feature you request is already implemented. To convert the value into a link simply set `url` property to the destination of your choice, it can be `http`, `mailto`, `tel` or any other schema recognizable by the browser. You can read more about this here: [link](https://github.com/KonradSzwarc/devscard/blob/main/src/types/shared.ts#L56)
> 
> That being said, we found room for improvement in this area. Namely, `target` attribute should be set to `_blank` only for HTTP links.
> 
> Also, sample data should indicate that it is possible to convert this value into a link.
> 
> I raised PR #210 with said improvements. Again thanks for raising this issue!

Thank you for the quick reply! @CaptainObjective 
Btw, the project is really amazing. I've already setup my own version and I am very satisfied with the result, feel free to check it out https://maciejhnat.dev/

I'll update it soon as you suggested 😎
