### ISSUE TITLE
Create Testimonial component

### ISSUE THREAD

**Issue by KonradSzwarc** [KonradSzwarc/devscard#22]
https://www.figma.com/file/pfFGe9f44nOVX1BtRoEBhg/Developer-vCard?node-id=111%3A2967
![image](https://user-images.githubusercontent.com/22938071/196254264-24ffde09-4d08-4c1f-aead-1d08dfe37c15.png)

**Comment by hoolek77** [comment]
W ramach tego issue, od razu zostanie dodana cała sekcja.
