### ISSUE TITLE
Getting 404 after running npm install

### ISSUE THREAD

**Issue by overgames** [KonradSzwarc/devscard#234]
Hello,
I forked this project to use and followed the doc provided. However, after running `npm install` I get the following error:
```
$ npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/files-pipe/-/files-pipe-0.0.7.tgz - Not found
npm ERR! 404
npm ERR! 404  'files-pipe@https://registry.npmjs.org/files-pipe/-/files-pipe-0.0.7.tgz' is not in this registry.     
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Am I doing something wrong? Any help is appreciated.

**Comment by hoolek77** [comment]
Hi @overgames 
The issue has been resolved. Pull the newest changes and you should be able to install dependencies 😄
